[font]
size = 14.2

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[window]
opacity = 0.6

[window.padding]
x = 5
y = 5

[terminal]
[shell]
program = "/run/current-system/sw/bin/zsh"

